package hu.progmasters.moovsmart.domain;

public enum PropertyHeatingType {
    GAS_CONVECTOR, CENTRAL_HEATING, DISTRICT_HEATING, ELECTRIC_BOILER, INFRARED_HEATING, HEARTH, GAS_FURNACE, DUAL_FUEL_FURNACE, OTHER_FURNACE, UNDERFLOOR_HEATING, WALL_HEATING, CEILING_COOLING_HEATING, HEAT_PUMP, OTHER, NO
}
